[character]
symbol = "❯❯"

[hostname]
ssh_only = false

[docker_context]
disabled = false

[username]
show_always = true
style_user = "white"

[git_branch]
symbol = " "

[custom.toolbox]
style = "bg:blue fg:bold black"
when = """ test -e /run/.toolboxenv """
command = "echo '⬢ toolbox'"
prefix = ""
